spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-microservice:
  greeting: "São"
  default-value: "Duas Pizzas"
